### ISSUE TITLE
Insufficient memory when opening a .psd file

### ISSUE THREAD

**Issue by haimat** [PsdPlugin/PsdPlugin#13]
I downloaded and installed your plugin, then started paint.net and tried to load a `.psd` file of mine.
However, that leads to the following error and stack trace in paint.net:

```
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at PaintDotNet.Data.PhotoshopFileType.PsdLoad.CheckSufficientMemory(PsdFile psdFile)
   at PhotoshopFile.PsdFile.LoadLayers(PsdBinaryReader reader, Boolean hasHeader)
   at PhotoshopFile.PsdFile.LoadLayerAndMaskInfo(PsdBinaryReader reader)
   at PhotoshopFile.PsdFile.Load(Stream stream, LoadContext loadContext)
   at PaintDotNet.Data.PhotoshopFileType.PsdLoad.Load(Stream input)
   at PaintDotNet.FileType.Load(Stream input) in D:\src\pdn\src\Data\FileType.cs:line 512
   at PaintDotNet.Functional.Func.Eval[T1,TRet](Func`2 f, T1 arg1) in D:\src\pdn\src\Base\Functional\Func.cs:line 158
```

I have 32gb system memory and that `.psd` fle is only 20mb in size.
Why does this error occur?

**Comment by taoyue** [comment]
Please read "Insufficient memory due to too many layers" here: https://www.psdplugin.com/docs/compatibility-with-photoshop/
