### ISSUE TITLE
Crash on images with complex layer masks

### ISSUE THREAD

**Issue by tannerhelland** [PsdPlugin/PsdPlugin#8]
Thank you for this excellent project.  

I get a hard crash on the latest Paint.NET (4.1.5) with the latest version of this plugin (2.5.0), when attempting to load this image from the psd-tools test library:

https://github.com/psd-tools/psd-tools/blob/master/tests/psd_files/layer_mask_data.psd

The paint.net error dialog reports:

> Application version: paint.net 4.1.5
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
> 
>    at PhotoshopFile.Channel.get_Rect()
> 
>    at PhotoshopFile.Channel.LoadPixelData(PsdBinaryReader reader)
> 
>    at PhotoshopFile.PsdFile.LoadLayers(PsdBinaryReader reader, Boolean hasHeader)
> 
>    at PhotoshopFile.PsdFile.LoadLayerAndMaskInfo(PsdBinaryReader reader)
> 
>    at PhotoshopFile.PsdFile.Load(Stream stream, LoadContext loadContext)
> 
>    at PaintDotNet.Data.PhotoshopFileType.PsdLoad.Load(Stream input)
> 
>    at PaintDotNet.FileType.Load(Stream input) in D:\src\pdn\src\Data\FileType.cs:line 495
> 
>    at PaintDotNet.Functional.Func.Eval[T1,TRet](Func`2 f, T1 arg1) in D:\src\pdn\src\Base\Functional\Func.cs:line 158

I think the problem may lie in the way the "Layer mask / adjustment layer data" segment is parsed in `Mask.cs`.  [Adobe's spec has multiple errors in this section](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_22582) so it gets confusing, but in particular, the If statement on line 134 of `Mask.cs`:

> // User mask is supplied separately when there is also a vector mask.
>       if (maskLength == 36)
> {

...is incorrect, I think.  In this PSD file, the layer mask segment is larger than 36 bytes (56 bytes), a condition the spec doesn't state explicitly but which is obviously possible if bit 4 of the Flags byte is set (which tells you to read a separate Parameter byte, which has additional flags indicating the presence of even MORE optional data).  I'm also fairly certain the parameter byte and optional data follows the Real User Mask segment, rather than occurring it before it as the spec implies.  (At least, this results in plausible data for all parsed values - but I don't have a copy of Photoshop to test more fully.)

Regardless, I believe the correct code should read something like:

> // User mask is supplied separately when there is also a vector mask.
>       if (maskLength >= 36)
> {

...to cover this case.  This prevents the current problem where the Real User Mask data is present, but ignored by the parser, likely causing the null rect at the source of the crash.

(The crash may also be caused by something else entirely, but hopefully this helps narrow it down a bit!)

**Comment by taoyue** [comment]
Thanks for the bug report.  The feature appears to have been introduced in Photoshop CS5, but the file structure wasn't documented until after CS6 was released.

I can't use the one-line fix, though.  I'll have to parse the structure.  There's also more than one bug here, because that PSD file is filled with edge cases.

**Comment by tannerhelland** [comment]
In case it's helpful, here are a few other test PSDs with "unexpected" layer mask segment sizes:

https://github.com/kyamagu/psd-tools2/blob/master/tests/psd_files/clipping-mask2.psd
https://github.com/kyamagu/psd-tools2/blob/master/tests/psd_files/mask_parameters.psd

([That repo](https://github.com/kyamagu/psd-tools2/tree/master/tests/psd_files) may have other useful images; I haven't examined them all in detail.)
